package androidx.emoji2.text;

import android.view.ViewGroup;
import java.util.Arrays;
import java.util.HashMap;

/* compiled from: r8-map-id-e3b6dc098cf6d613ac4f8e65c38618200d3974a931f86dcb452a3625706b4731 */
/* loaded from: classes.dex */
public final class nz {

    /* renamed from: a, reason: collision with root package name */
    public int f833a;
    public final qz b;
    public final pz c;
    public final oz d;
    public final rz e;
    public HashMap f;

    public nz() {
        qz qzVar = new qz();
        qzVar.f986a = 0;
        qzVar.b = 0;
        qzVar.c = 1.0f;
        qzVar.d = Float.NaN;
        this.b = qzVar;
        pz pzVar = new pz();
        pzVar.f934a = -1;
        pzVar.b = 0;
        pzVar.c = -1;
        pzVar.d = Float.NaN;
        pzVar.e = Float.NaN;
        pzVar.f = Float.NaN;
        pzVar.g = -1;
        pzVar.h = null;
        pzVar.i = -1;
        this.c = pzVar;
        oz ozVar = new oz();
        ozVar.f881a = false;
        ozVar.d = -1;
        ozVar.e = -1;
        ozVar.f = -1.0f;
        ozVar.g = true;
        ozVar.h = -1;
        ozVar.i = -1;
        ozVar.j = -1;
        ozVar.k = -1;
        ozVar.l = -1;
        ozVar.m = -1;
        ozVar.n = -1;
        ozVar.o = -1;
        ozVar.p = -1;
        ozVar.q = -1;
        ozVar.r = -1;
        ozVar.s = -1;
        ozVar.t = -1;
        ozVar.u = -1;
        ozVar.v = -1;
        ozVar.w = 0.5f;
        ozVar.x = 0.5f;
        ozVar.y = null;
        ozVar.z = -1;
        ozVar.A = 0;
        ozVar.B = 0.0f;
        ozVar.C = -1;
        ozVar.D = -1;
        ozVar.E = -1;
        ozVar.F = 0;
        ozVar.G = 0;
        ozVar.H = 0;
        ozVar.I = 0;
        ozVar.J = 0;
        ozVar.K = 0;
        ozVar.L = 0;
        ozVar.M = Integer.MIN_VALUE;
        ozVar.N = Integer.MIN_VALUE;
        ozVar.O = Integer.MIN_VALUE;
        ozVar.P = Integer.MIN_VALUE;
        ozVar.Q = Integer.MIN_VALUE;
        ozVar.R = Integer.MIN_VALUE;
        ozVar.S = Integer.MIN_VALUE;
        ozVar.T = -1.0f;
        ozVar.U = -1.0f;
        ozVar.V = 0;
        ozVar.W = 0;
        ozVar.X = 0;
        ozVar.Y = 0;
        ozVar.Z = 0;
        ozVar.a0 = 0;
        ozVar.b0 = 0;
        ozVar.c0 = 0;
        ozVar.d0 = 1.0f;
        ozVar.e0 = 1.0f;
        ozVar.f0 = -1;
        ozVar.g0 = 0;
        ozVar.h0 = -1;
        ozVar.l0 = false;
        ozVar.m0 = false;
        ozVar.n0 = true;
        ozVar.o0 = 0;
        this.d = ozVar;
        rz rzVar = new rz();
        rzVar.f1041a = 0.0f;
        rzVar.b = 0.0f;
        rzVar.c = 0.0f;
        rzVar.d = 1.0f;
        rzVar.e = 1.0f;
        rzVar.f = Float.NaN;
        rzVar.g = Float.NaN;
        rzVar.h = -1;
        rzVar.i = 0.0f;
        rzVar.j = 0.0f;
        rzVar.k = 0.0f;
        rzVar.l = false;
        rzVar.m = 0.0f;
        this.e = rzVar;
        this.f = new HashMap();
    }

    public final void a(iz izVar) {
        oz ozVar = this.d;
        izVar.e = ozVar.h;
        izVar.f = ozVar.i;
        izVar.g = ozVar.j;
        izVar.h = ozVar.k;
        izVar.i = ozVar.l;
        izVar.j = ozVar.m;
        izVar.k = ozVar.n;
        izVar.l = ozVar.o;
        izVar.m = ozVar.p;
        izVar.n = ozVar.q;
        izVar.o = ozVar.r;
        izVar.s = ozVar.s;
        izVar.t = ozVar.t;
        izVar.u = ozVar.u;
        izVar.v = ozVar.v;
        ((ViewGroup.MarginLayoutParams) izVar).leftMargin = ozVar.F;
        ((ViewGroup.MarginLayoutParams) izVar).rightMargin = ozVar.G;
        ((ViewGroup.MarginLayoutParams) izVar).topMargin = ozVar.H;
        ((ViewGroup.MarginLayoutParams) izVar).bottomMargin = ozVar.I;
        izVar.A = ozVar.R;
        izVar.B = ozVar.Q;
        izVar.x = ozVar.N;
        izVar.z = ozVar.P;
        izVar.E = ozVar.w;
        izVar.F = ozVar.x;
        izVar.p = ozVar.z;
        izVar.q = ozVar.A;
        izVar.r = ozVar.B;
        izVar.G = ozVar.y;
        izVar.T = ozVar.C;
        izVar.U = ozVar.D;
        izVar.I = ozVar.T;
        izVar.H = ozVar.U;
        izVar.K = ozVar.W;
        izVar.J = ozVar.V;
        izVar.W = ozVar.l0;
        izVar.X = ozVar.m0;
        izVar.L = ozVar.X;
        izVar.M = ozVar.Y;
        izVar.P = ozVar.Z;
        izVar.Q = ozVar.a0;
        izVar.N = ozVar.b0;
        izVar.O = ozVar.c0;
        izVar.R = ozVar.d0;
        izVar.S = ozVar.e0;
        izVar.V = ozVar.E;
        izVar.c = ozVar.f;
        izVar.f556a = ozVar.d;
        izVar.b = ozVar.e;
        ((ViewGroup.MarginLayoutParams) izVar).width = ozVar.b;
        ((ViewGroup.MarginLayoutParams) izVar).height = ozVar.c;
        String str = ozVar.k0;
        if (str != null) {
            izVar.Y = str;
        }
        izVar.Z = ozVar.o0;
        izVar.setMarginStart(ozVar.K);
        izVar.setMarginEnd(ozVar.J);
        izVar.a();
    }

    public final Object clone() {
        nz nzVar = new nz();
        oz ozVar = nzVar.d;
        ozVar.getClass();
        oz ozVar2 = this.d;
        ozVar.f881a = ozVar2.f881a;
        ozVar.b = ozVar2.b;
        ozVar.c = ozVar2.c;
        ozVar.d = ozVar2.d;
        ozVar.e = ozVar2.e;
        ozVar.f = ozVar2.f;
        ozVar.g = ozVar2.g;
        ozVar.h = ozVar2.h;
        ozVar.i = ozVar2.i;
        ozVar.j = ozVar2.j;
        ozVar.k = ozVar2.k;
        ozVar.l = ozVar2.l;
        ozVar.m = ozVar2.m;
        ozVar.n = ozVar2.n;
        ozVar.o = ozVar2.o;
        ozVar.p = ozVar2.p;
        ozVar.q = ozVar2.q;
        ozVar.r = ozVar2.r;
        ozVar.s = ozVar2.s;
        ozVar.t = ozVar2.t;
        ozVar.u = ozVar2.u;
        ozVar.v = ozVar2.v;
        ozVar.w = ozVar2.w;
        ozVar.x = ozVar2.x;
        ozVar.y = ozVar2.y;
        ozVar.z = ozVar2.z;
        ozVar.A = ozVar2.A;
        ozVar.B = ozVar2.B;
        ozVar.C = ozVar2.C;
        ozVar.D = ozVar2.D;
        ozVar.E = ozVar2.E;
        ozVar.F = ozVar2.F;
        ozVar.G = ozVar2.G;
        ozVar.H = ozVar2.H;
        ozVar.I = ozVar2.I;
        ozVar.J = ozVar2.J;
        ozVar.K = ozVar2.K;
        ozVar.L = ozVar2.L;
        ozVar.M = ozVar2.M;
        ozVar.N = ozVar2.N;
        ozVar.O = ozVar2.O;
        ozVar.P = ozVar2.P;
        ozVar.Q = ozVar2.Q;
        ozVar.R = ozVar2.R;
        ozVar.S = ozVar2.S;
        ozVar.T = ozVar2.T;
        ozVar.U = ozVar2.U;
        ozVar.V = ozVar2.V;
        ozVar.W = ozVar2.W;
        ozVar.X = ozVar2.X;
        ozVar.Y = ozVar2.Y;
        ozVar.Z = ozVar2.Z;
        ozVar.a0 = ozVar2.a0;
        ozVar.b0 = ozVar2.b0;
        ozVar.c0 = ozVar2.c0;
        ozVar.d0 = ozVar2.d0;
        ozVar.e0 = ozVar2.e0;
        ozVar.f0 = ozVar2.f0;
        ozVar.g0 = ozVar2.g0;
        ozVar.h0 = ozVar2.h0;
        ozVar.k0 = ozVar2.k0;
        int[] iArr = ozVar2.i0;
        if (iArr == null || ozVar2.j0 != null) {
            ozVar.i0 = null;
        } else {
            ozVar.i0 = Arrays.copyOf(iArr, iArr.length);
        }
        ozVar.j0 = ozVar2.j0;
        ozVar.l0 = ozVar2.l0;
        ozVar.m0 = ozVar2.m0;
        ozVar.n0 = ozVar2.n0;
        ozVar.o0 = ozVar2.o0;
        pz pzVar = nzVar.c;
        pzVar.getClass();
        pz pzVar2 = this.c;
        pzVar2.getClass();
        pzVar.f934a = pzVar2.f934a;
        pzVar.c = pzVar2.c;
        pzVar.e = pzVar2.e;
        pzVar.d = pzVar2.d;
        qz qzVar = this.b;
        int i = qzVar.f986a;
        qz qzVar2 = nzVar.b;
        qzVar2.f986a = i;
        qzVar2.c = qzVar.c;
        qzVar2.d = qzVar.d;
        qzVar2.b = qzVar.b;
        rz rzVar = nzVar.e;
        rzVar.getClass();
        rz rzVar2 = this.e;
        rzVar2.getClass();
        rzVar.f1041a = rzVar2.f1041a;
        rzVar.b = rzVar2.b;
        rzVar.c = rzVar2.c;
        rzVar.d = rzVar2.d;
        rzVar.e = rzVar2.e;
        rzVar.f = rzVar2.f;
        rzVar.g = rzVar2.g;
        rzVar.h = rzVar2.h;
        rzVar.i = rzVar2.i;
        rzVar.j = rzVar2.j;
        rzVar.k = rzVar2.k;
        rzVar.l = rzVar2.l;
        rzVar.m = rzVar2.m;
        nzVar.f833a = this.f833a;
        return nzVar;
    }
}
