package androidx.emoji2.text;

/* compiled from: r8-map-id-e3b6dc098cf6d613ac4f8e65c38618200d3974a931f86dcb452a3625706b4731 */
/* loaded from: classes.dex */
public abstract class yo2 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final zl0 D;
    public static final un0 E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final zl0 I;
    public static final un0 J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final zl0 N;
    public static final un0 O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final zl0 S;
    public static final un0 T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final zl0 X;
    public static final un0 Y;
    public static final long Z;

    /* renamed from: a, reason: collision with root package name */
    public static final un0 f1394a;
    public static final long a0;
    public static final long b;
    public static final long b0;
    public static final long c;
    public static final zl0 c0;
    public static final long d;
    public static final un0 d0;
    public static final zl0 e;
    public static final long e0;
    public static final un0 f;
    public static final long f0;
    public static final long g;
    public static final long g0;
    public static final long h;
    public static final zl0 h0;
    public static final long i;
    public static final un0 i0;
    public static final zl0 j;
    public static final long j0;
    public static final un0 k;
    public static final long k0;
    public static final long l;
    public static final long l0;
    public static final long m;
    public static final zl0 m0;
    public static final long n;
    public static final un0 n0;
    public static final zl0 o;
    public static final long o0;
    public static final un0 p;
    public static final long p0;
    public static final long q;
    public static final long q0;
    public static final long r;
    public static final zl0 r0;
    public static final long s;
    public static final un0 s0;
    public static final zl0 t;
    public static final long t0;
    public static final un0 u;
    public static final long u0;
    public static final long v;
    public static final long v0;
    public static final long w;
    public static final zl0 w0;
    public static final long x;
    public static final zl0 y;
    public static final un0 z;

    static {
        zl0 zl0Var = lp2.f702a;
        un0 un0Var = vh2.b;
        f1394a = un0Var;
        b = nz0.C(24.0d);
        c = nz0.D(16);
        d = nz0.C(0.5d);
        zl0 zl0Var2 = lp2.b;
        e = zl0Var2;
        f = un0Var;
        g = nz0.C(20.0d);
        h = nz0.D(14);
        i = nz0.C(0.2d);
        j = zl0Var2;
        k = un0Var;
        l = nz0.C(16.0d);
        m = nz0.D(12);
        n = nz0.C(0.4d);
        o = zl0Var2;
        p = un0Var;
        q = nz0.C(64.0d);
        r = nz0.D(57);
        long C2 = nz0.C(0.2d);
        kl2[] kl2VarArr = jl2.b;
        long j2 = C2 & 1095216660480L;
        if (j2 == 0) {
            kv0.a("Cannot perform operation for Unspecified type.");
        }
        s = nz0.H(-jl2.c(C2), j2);
        t = zl0Var2;
        u = un0Var;
        v = nz0.C(52.0d);
        w = nz0.D(45);
        x = nz0.C(0.0d);
        y = zl0Var2;
        z = un0Var;
        A = nz0.C(44.0d);
        B = nz0.D(36);
        C = nz0.C(0.0d);
        D = zl0Var2;
        E = un0Var;
        F = nz0.C(40.0d);
        G = nz0.D(32);
        H = nz0.C(0.0d);
        I = zl0Var2;
        J = un0Var;
        K = nz0.C(36.0d);
        L = nz0.D(28);
        M = nz0.C(0.0d);
        N = zl0Var2;
        O = un0Var;
        P = nz0.C(32.0d);
        Q = nz0.D(24);
        R = nz0.C(0.0d);
        S = zl0Var2;
        T = un0Var;
        U = nz0.C(20.0d);
        V = nz0.D(14);
        W = nz0.C(0.1d);
        zl0 zl0Var3 = lp2.f702a;
        X = zl0Var3;
        Y = un0Var;
        Z = nz0.C(16.0d);
        a0 = nz0.D(12);
        b0 = nz0.C(0.5d);
        c0 = zl0Var3;
        d0 = un0Var;
        e0 = nz0.C(16.0d);
        f0 = nz0.D(11);
        g0 = nz0.C(0.5d);
        h0 = zl0Var3;
        i0 = un0Var;
        j0 = nz0.C(28.0d);
        k0 = nz0.D(22);
        l0 = nz0.C(0.0d);
        m0 = zl0Var2;
        n0 = un0Var;
        o0 = nz0.C(24.0d);
        p0 = nz0.D(16);
        q0 = nz0.C(0.2d);
        r0 = zl0Var3;
        s0 = un0Var;
        t0 = nz0.C(20.0d);
        u0 = nz0.D(14);
        v0 = nz0.C(0.1d);
        w0 = zl0Var3;
    }
}
